spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relatorio_tecnico?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Tujad&99
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # use "create" na primeira vez, depois mude para "update"
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: America/Sao_Paulo

server:
  address: 0.0.0.0
  port: 8080